Time: 2025-05-12T13:25:21.535756700
Exception message: Could not register item due to system error
se.kth.iv1350.processSale.controller.ItemRegistrationFailureException: Could not register item due to system error
	at se.kth.iv1350.processSale.controller.Controller.registerNewItem(Controller.java:79)
	at se.kth.iv1350.processSale.view.View.runFakeExecution(View.java:57)
	at se.kth.iv1350.processSale.startup.Main.main(Main.java:32)
Caused by: se.kth.iv1350.processSale.integration.DataBaseFailureException: Database failure occurred while searching for item with ID: 7891
	at se.kth.iv1350.processSale.integration.InventorySystem.simulateDataBaseFailure(InventorySystem.java:69)
	at se.kth.iv1350.processSale.integration.InventorySystem.validateIdentifier(InventorySystem.java:43)
	at se.kth.iv1350.processSale.controller.Controller.registerNewItem(Controller.java:65)
	... 2 more
--------------------------------------------------
Date: 2025-05-12
Time: 13:26:41.286990600
Exception message: Could not register item due to system error
se.kth.iv1350.processSale.controller.ItemRegistrationFailureException: Could not register item due to system error
	at se.kth.iv1350.processSale.controller.Controller.registerNewItem(Controller.java:79)
	at se.kth.iv1350.processSale.view.View.runFakeExecution(View.java:57)
	at se.kth.iv1350.processSale.startup.Main.main(Main.java:32)
Caused by: se.kth.iv1350.processSale.integration.DataBaseFailureException: Database failure occurred while searching for item with ID: 7891
	at se.kth.iv1350.processSale.integration.InventorySystem.simulateDataBaseFailure(InventorySystem.java:69)
	at se.kth.iv1350.processSale.integration.InventorySystem.validateIdentifier(InventorySystem.java:43)
	at se.kth.iv1350.processSale.controller.Controller.registerNewItem(Controller.java:65)
	... 2 more
--------------------------------------------------
Date: 2025-05-12
Time: 15:23:31.427941900
Exception message: Could not register item due to system error
se.kth.iv1350.processSale.controller.ItemRegistrationFailureException: Could not register item due to system error
	at se.kth.iv1350.processSale.controller.Controller.registerNewItem(Controller.java:78)
	at se.kth.iv1350.processSale.view.View.runFakeExecution(View.java:73)
	at se.kth.iv1350.processSale.startup.Main.main(Main.java:33)
Caused by: se.kth.iv1350.processSale.integration.DataBaseFailureException: Database failure occurred while searching for item with ID: 7891
	at se.kth.iv1350.processSale.integration.InventorySystem.simulateDataBaseFailure(InventorySystem.java:70)
	at se.kth.iv1350.processSale.integration.InventorySystem.validateIdentifier(InventorySystem.java:44)
	at se.kth.iv1350.processSale.controller.Controller.registerNewItem(Controller.java:72)
	... 2 more
--------------------------------------------------
Date: 2025-05-13
Time: 16:34:53.186134400
Exception message: Could not register item due to system error
se.kth.iv1350.processSale.controller.ItemRegistrationFailureException: Could not register item due to system error
	at se.kth.iv1350.processSale.controller.Controller.registerNewItem(Controller.java:79)
	at se.kth.iv1350.processSale.view.View.runFakeExecution(View.java:73)
	at se.kth.iv1350.processSale.startup.Main.main(Main.java:33)
Caused by: se.kth.iv1350.processSale.integration.DataBaseFailureException: Database failure occurred while searching for item with ID: 7891
	at se.kth.iv1350.processSale.integration.InventorySystem.simulateDataBaseFailure(InventorySystem.java:71)
	at se.kth.iv1350.processSale.integration.InventorySystem.validateIdentifier(InventorySystem.java:45)
	at se.kth.iv1350.processSale.controller.Controller.registerNewItem(Controller.java:73)
	... 2 more
--------------------------------------------------
Date: 2025-05-16
Time: 13:50:47.999117800
Exception message: Could not register item due to system error
se.kth.iv1350.processSale.controller.ItemRegistrationFailureException: Could not register item due to system error
	at se.kth.iv1350.processSale.controller.Controller.registerNewItem(Controller.java:79)
	at se.kth.iv1350.processSale.view.View.runFakeExecution(View.java:73)
	at se.kth.iv1350.processSale.startup.Main.main(Main.java:33)
Caused by: se.kth.iv1350.processSale.integration.DataBaseFailureException: Database failure occurred while searching for item with ID: 7891
	at se.kth.iv1350.processSale.integration.InventorySystem.simulateDataBaseFailure(InventorySystem.java:71)
	at se.kth.iv1350.processSale.integration.InventorySystem.validateIdentifier(InventorySystem.java:45)
	at se.kth.iv1350.processSale.controller.Controller.registerNewItem(Controller.java:73)
	... 2 more
--------------------------------------------------
Date: 2025-05-16
Time: 14:19:52.187498400
Exception message: Database failure occurred while searching for item with ID: 7891
se.kth.iv1350.processSale.integration.DataBaseFailureException: Database failure occurred while searching for item with ID: 7891
	at se.kth.iv1350.processSale.integration.InventorySystem.simulateDataBaseFailure(InventorySystem.java:71)
	at se.kth.iv1350.processSale.integration.InventorySystem.validateIdentifier(InventorySystem.java:45)
	at se.kth.iv1350.processSale.controller.Controller.registerNewItem(Controller.java:76)
	at se.kth.iv1350.processSale.view.View.runFakeExecution(View.java:70)
	at se.kth.iv1350.processSale.startup.Main.main(Main.java:34)
--------------------------------------------------
Date: 2025-05-16
Time: 14:21:09.222838700
Exception message: Database failure occurred while searching for item with ID: 7891
se.kth.iv1350.processSale.integration.DataBaseFailureException: Database failure occurred while searching for item with ID: 7891
	at se.kth.iv1350.processSale.integration.InventorySystem.simulateDataBaseFailure(InventorySystem.java:71)
	at se.kth.iv1350.processSale.integration.InventorySystem.validateIdentifier(InventorySystem.java:45)
	at se.kth.iv1350.processSale.controller.Controller.registerNewItem(Controller.java:76)
	at se.kth.iv1350.processSale.view.View.runFakeExecution(View.java:70)
	at se.kth.iv1350.processSale.startup.Main.main(Main.java:34)
--------------------------------------------------
Date: 2025-05-16
Time: 14:23:48.899918400
Exception message: Database failure occurred while searching for item with ID: 7891
se.kth.iv1350.processSale.integration.DataBaseFailureException: Database failure occurred while searching for item with ID: 7891
	at se.kth.iv1350.processSale.integration.InventorySystem.simulateDataBaseFailure(InventorySystem.java:71)
	at se.kth.iv1350.processSale.integration.InventorySystem.validateIdentifier(InventorySystem.java:45)
	at se.kth.iv1350.processSale.controller.Controller.registerNewItem(Controller.java:76)
	at se.kth.iv1350.processSale.view.View.runFakeExecution(View.java:70)
	at se.kth.iv1350.processSale.startup.Main.main(Main.java:34)
--------------------------------------------------
Date: 2025-05-16
Time: 14:24:34.259710100
Exception message: Database failure occurred while searching for item with ID: 7891
se.kth.iv1350.processSale.integration.DataBaseFailureException: Database failure occurred while searching for item with ID: 7891
	at se.kth.iv1350.processSale.integration.InventorySystem.simulateDataBaseFailure(InventorySystem.java:71)
	at se.kth.iv1350.processSale.integration.InventorySystem.validateIdentifier(InventorySystem.java:45)
	at se.kth.iv1350.processSale.controller.Controller.registerNewItem(Controller.java:76)
	at se.kth.iv1350.processSale.view.View.runFakeExecution(View.java:70)
	at se.kth.iv1350.processSale.startup.Main.main(Main.java:34)
--------------------------------------------------
Date: 2025-05-16
Time: 14:28:09.859696600
Exception message: Database failure occurred while searching for item with ID: 7891
se.kth.iv1350.processSale.integration.DataBaseFailureException: Database failure occurred while searching for item with ID: 7891
	at se.kth.iv1350.processSale.integration.InventorySystem.simulateDataBaseFailure(InventorySystem.java:71)
	at se.kth.iv1350.processSale.integration.InventorySystem.validateIdentifier(InventorySystem.java:45)
	at se.kth.iv1350.processSale.controller.Controller.registerNewItem(Controller.java:76)
	at se.kth.iv1350.processSale.view.View.runFakeExecution(View.java:70)
	at se.kth.iv1350.processSale.startup.Main.main(Main.java:34)
--------------------------------------------------
Date: 2025-05-16
Time: 14:29:14.104505800
Exception message: Database failure occurred while searching for item with ID: 7891
se.kth.iv1350.processSale.integration.DataBaseFailureException: Database failure occurred while searching for item with ID: 7891
	at se.kth.iv1350.processSale.integration.InventorySystem.simulateDataBaseFailure(InventorySystem.java:71)
	at se.kth.iv1350.processSale.integration.InventorySystem.validateIdentifier(InventorySystem.java:45)
	at se.kth.iv1350.processSale.controller.Controller.registerNewItem(Controller.java:76)
	at se.kth.iv1350.processSale.view.View.runFakeExecution(View.java:70)
	at se.kth.iv1350.processSale.startup.Main.main(Main.java:34)
--------------------------------------------------
Date: 2025-05-16
Time: 14:31:15.507320200
Exception message: Database failure occurred while searching for item with ID: 7891
se.kth.iv1350.processSale.integration.DataBaseFailureException: Database failure occurred while searching for item with ID: 7891
	at se.kth.iv1350.processSale.integration.InventorySystem.simulateDataBaseFailure(InventorySystem.java:71)
	at se.kth.iv1350.processSale.integration.InventorySystem.validateIdentifier(InventorySystem.java:45)
	at se.kth.iv1350.processSale.controller.Controller.registerNewItem(Controller.java:76)
	at se.kth.iv1350.processSale.view.View.runFakeExecution(View.java:70)
	at se.kth.iv1350.processSale.startup.Main.main(Main.java:34)
--------------------------------------------------
Date: 2025-05-16
Time: 14:32:46.979526400
Exception message: Database failure occurred while searching for item with ID: 7891
se.kth.iv1350.processSale.integration.DataBaseFailureException: Database failure occurred while searching for item with ID: 7891
	at se.kth.iv1350.processSale.integration.InventorySystem.simulateDataBaseFailure(InventorySystem.java:71)
	at se.kth.iv1350.processSale.integration.InventorySystem.validateIdentifier(InventorySystem.java:45)
	at se.kth.iv1350.processSale.controller.Controller.registerNewItem(Controller.java:76)
	at se.kth.iv1350.processSale.view.View.runFakeExecution(View.java:70)
	at se.kth.iv1350.processSale.startup.Main.main(Main.java:34)
--------------------------------------------------
Date: 2025-05-16
Time: 14:34:52.297534700
Exception message: Database failure occurred while searching for item with ID: 7891
se.kth.iv1350.processSale.integration.DataBaseFailureException: Database failure occurred while searching for item with ID: 7891
	at se.kth.iv1350.processSale.integration.InventorySystem.simulateDataBaseFailure(InventorySystem.java:71)
	at se.kth.iv1350.processSale.integration.InventorySystem.validateIdentifier(InventorySystem.java:45)
	at se.kth.iv1350.processSale.controller.Controller.registerNewItem(Controller.java:76)
	at se.kth.iv1350.processSale.view.View.runFakeExecution(View.java:71)
	at se.kth.iv1350.processSale.startup.Main.main(Main.java:34)
--------------------------------------------------
Date: 2025-05-16
Time: 14:37:00.505147100
Exception message: Database failure occurred while searching for item with ID: 7891
se.kth.iv1350.processSale.integration.DataBaseFailureException: Database failure occurred while searching for item with ID: 7891
	at se.kth.iv1350.processSale.integration.InventorySystem.simulateDataBaseFailure(InventorySystem.java:71)
	at se.kth.iv1350.processSale.integration.InventorySystem.validateIdentifier(InventorySystem.java:45)
	at se.kth.iv1350.processSale.controller.Controller.registerNewItem(Controller.java:76)
	at se.kth.iv1350.processSale.view.View.runFakeExecution(View.java:70)
	at se.kth.iv1350.processSale.startup.Main.main(Main.java:34)
--------------------------------------------------
Date: 2025-05-16
Time: 14:38:18.373944600
Exception message: Database failure occurred while searching for item with ID: 7891
se.kth.iv1350.processSale.integration.DataBaseFailureException: Database failure occurred while searching for item with ID: 7891
	at se.kth.iv1350.processSale.integration.InventorySystem.simulateDataBaseFailure(InventorySystem.java:71)
	at se.kth.iv1350.processSale.integration.InventorySystem.validateIdentifier(InventorySystem.java:45)
	at se.kth.iv1350.processSale.controller.Controller.registerNewItem(Controller.java:76)
	at se.kth.iv1350.processSale.view.View.runFakeExecution(View.java:70)
	at se.kth.iv1350.processSale.startup.Main.main(Main.java:34)
--------------------------------------------------
Date: 2025-05-16
Time: 14:43:17.196180600
Exception message: Database failure occurred while searching for item with ID: 7891
se.kth.iv1350.processSale.integration.DataBaseFailureException: Database failure occurred while searching for item with ID: 7891
	at se.kth.iv1350.processSale.integration.InventorySystem.simulateDataBaseFailure(InventorySystem.java:71)
	at se.kth.iv1350.processSale.integration.InventorySystem.validateIdentifier(InventorySystem.java:45)
	at se.kth.iv1350.processSale.controller.Controller.registerNewItem(Controller.java:76)
	at se.kth.iv1350.processSale.view.View.runFakeExecution(View.java:70)
	at se.kth.iv1350.processSale.startup.Main.main(Main.java:34)
--------------------------------------------------
Date: 2025-05-16
Time: 15:01:20.107183400
Exception message: Database failure occurred while searching for item with ID: 7891
se.kth.iv1350.processSale.integration.DataBaseFailureException: Database failure occurred while searching for item with ID: 7891
	at se.kth.iv1350.processSale.integration.InventorySystem.simulateDataBaseFailure(InventorySystem.java:71)
	at se.kth.iv1350.processSale.integration.InventorySystem.validateIdentifier(InventorySystem.java:45)
	at se.kth.iv1350.processSale.controller.Controller.registerNewItem(Controller.java:76)
	at se.kth.iv1350.processSale.view.View.runFakeExecution(View.java:70)
	at se.kth.iv1350.processSale.startup.Main.main(Main.java:34)
--------------------------------------------------
Date: 2025-05-17
Time: 15:54:21.170060700
Exception message: Database failure occurred while searching for item with ID: 7891
se.kth.iv1350.processSale.integration.DataBaseFailureException: Database failure occurred while searching for item with ID: 7891
	at se.kth.iv1350.processSale.integration.InventorySystem.simulateDataBaseFailure(InventorySystem.java:71)
	at se.kth.iv1350.processSale.integration.InventorySystem.validateIdentifier(InventorySystem.java:45)
	at se.kth.iv1350.processSale.controller.Controller.registerNewItem(Controller.java:77)
	at se.kth.iv1350.processSale.view.View.runFakeExecution(View.java:69)
	at se.kth.iv1350.processSale.startup.Main.main(Main.java:34)
--------------------------------------------------
Date: 2025-05-17
Time: 17:11:25.193726
Exception message: Database failure occurred while searching for item with ID: 7891
se.kth.iv1350.processSale.integration.DataBaseFailureException: Database failure occurred while searching for item with ID: 7891
	at se.kth.iv1350.processSale.integration.InventorySystem.simulateDataBaseFailure(InventorySystem.java:71)
	at se.kth.iv1350.processSale.integration.InventorySystem.validateIdentifier(InventorySystem.java:45)
	at se.kth.iv1350.processSale.controller.Controller.registerNewItem(Controller.java:77)
	at se.kth.iv1350.processSale.view.View.runFakeExecution(View.java:70)
	at se.kth.iv1350.processSale.startup.Main.main(Main.java:34)
--------------------------------------------------
Date: 2025-05-19
Time: 14:50:26.524944800
Exception message: Database failure occurred while searching for item with ID: 7891
se.kth.iv1350.processSale.integration.DataBaseFailureException: Database failure occurred while searching for item with ID: 7891
	at se.kth.iv1350.processSale.integration.InventorySystem.simulateDataBaseFailure(InventorySystem.java:71)
	at se.kth.iv1350.processSale.integration.InventorySystem.validateIdentifier(InventorySystem.java:45)
	at se.kth.iv1350.processSale.controller.Controller.registerNewItem(Controller.java:84)
	at se.kth.iv1350.processSale.view.View.runFakeExecution(View.java:70)
	at se.kth.iv1350.processSale.startup.Main.main(Main.java:35)
--------------------------------------------------
Date: 2025-05-19
Time: 14:50:34.933279300
Exception message: Database failure occurred while searching for item with ID: 7891
se.kth.iv1350.processSale.integration.DataBaseFailureException: Database failure occurred while searching for item with ID: 7891
	at se.kth.iv1350.processSale.integration.InventorySystem.simulateDataBaseFailure(InventorySystem.java:71)
	at se.kth.iv1350.processSale.integration.InventorySystem.validateIdentifier(InventorySystem.java:45)
	at se.kth.iv1350.processSale.controller.Controller.registerNewItem(Controller.java:84)
	at se.kth.iv1350.processSale.view.View.runFakeExecution(View.java:70)
	at se.kth.iv1350.processSale.startup.Main.main(Main.java:35)
--------------------------------------------------
